{% set name = "fastjsonschema" %}
{% set version = "2.14.3" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ba706f65bef0d3a511e514223f47ea0835385022b32cd77efa7b251f0991d93e
  - folder: src
    url: https://github.com/horejsek/python-{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 1f5f766e04b2b34711dae56b1ff33e741a21f346aab151cfd061edd9c2e2ce6f

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3

test:
  source_files:
    - src/tests
  requires:
    - pytest-cov
    - pytest-benchmark
  imports:
    - fastjsonschema
  commands:
    - cd src && cd tests && pytest --cov fastjsonschema -k "not compile_to_code_ipv6_regex"

about:
  home: https://github.com/horejsek/python-fastjsonschema
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Fastest Python implementation of JSON schema
  description: |
    fastjsonschema implements validation of JSON documents by JSON schema. The
    library implements JSON schema drafts 04, 06 and 07. The main purpose is to
    have a really fast implementation.
  doc_url: https://horejsek.github.io/python-fastjsonschema
  doc_source_url: https://github.com/horejsek/python-fastjsonschema/tree/master/docs

extra:
  recipe-maintainers:
    - bollwyvl
