{% set version = "2.21.2" %}

package:
  name: python-fastjsonschema
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fastjsonschema/fastjsonschema-{{ version }}.tar.gz
  sha256: b1eb43748041c880796cd077f1a07c3d94e93ae84bba5ed36800a33554ae05de

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
  imports:
    - fastjsonschema
  commands:
    - cd tests && pytest -vv -m "not benchmark"
    - pip check

about:
  home: https://github.com/horejsek/python-fastjsonschema
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fastest Python implementation of JSON schema
  description: |
    fastjsonschema implements validation of JSON documents by JSON schema. The
    library implements JSON schema drafts 04, 06 and 07. The main purpose is to
    have a really fast implementation.
  dev_url: https://github.com/horejsek/python-fastjsonschema
  doc_url: https://horejsek.github.io/python-fastjsonschema
  doc_source_url: https://github.com/horejsek/python-fastjsonschema/tree/master/docs

extra:
  recipe-maintainers:
    - bollwyvl
