{% set name = "fastjsonschema" %}
{% set version = "2.15.0" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: e1ecba260bcffb7de0dda6aee74261da1e6dccde5ee04c1170b2dd97d2b87676
  - folder: src
    url: https://github.com/horejsek/python-{{ name }}/archive/v{{ version }}.tar.gz
    sha256: e85ce78cee9edaf45d9d58326190086ba4a5fb96ea4d7be9662dfdf2d2fb62ab

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3

test:
  source_files:
    - src/tests
  requires:
    - pytest-cov
    - pytest-benchmark
  imports:
    - fastjsonschema
  commands:
    - cd src && cd tests && pytest --cov fastjsonschema -k "not compile_to_code_ipv6_regex"

about:
  home: https://github.com/horejsek/python-fastjsonschema
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Fastest Python implementation of JSON schema
  description: |
    fastjsonschema implements validation of JSON documents by JSON schema. The
    library implements JSON schema drafts 04, 06 and 07. The main purpose is to
    have a really fast implementation.
  doc_url: https://horejsek.github.io/python-fastjsonschema
  doc_source_url: https://github.com/horejsek/python-fastjsonschema/tree/master/docs

extra:
  recipe-maintainers:
    - bollwyvl
